apiVersion: "v1"
kind: "Service"
metadata:
  name: "generator-deployment-service"
  namespace: "default"
  labels:
    app: "generator"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  selector:
    app: "generator"
  type: "LoadBalancer"
  loadBalancerIP: ""

